### ISSUE TITLE
Fix victims saved location and fix design 

### ISSUE THREAD

**Issue by Kokojo21** [siddhant385/django-phishing#2]
**Describe the bug**
1- The big and important problem is that the data ( victims data email pass ) not saved in database and i cant see it from admin panel .

2- the layout ( design) for pages is very bad need to improve .

I like the website but please update it and fix these problems

**Comment by siddhant385** [comment]
> **Describe the bug** 1- The big and important problem is that the data ( victims data email pass ) not saved in database and i cant see it from admin panel .
> 
> 2- the layout ( design) for pages is very bad need to improve .
> 
> I like the website but please update it and fix these problems

Hey Mate Sorry For late reply
This tool I was created was for learning about django framework but using django for such a lightweight task is not recommended so i am recreating whole as flask application which will be easy to configure and deploy so till then please wait
**The new Tool will be visible in my repo in some days**
